### ISSUE TITLE
Don't use Dict comprehensions and therefore support Python 2.6

### ISSUE THREAD

**Issue by gleeda** [williballenthin/EVTXtract#3]
Just got this error on the latest build:

<pre>
File "extract_valid_evtx_records_and_templates.py", line 35
    _replacement_patterns = {i: re.compile("\[(Normal|Conditional) Substitution\(index=%d, type=\d+\)\]" % i) for i in
                                                                                                                ^
SyntaxError: invalid syntax
</pre>

Maybe i've done something weird?

<pre>
$ find FILES/ -type f -exec python extract_valid_evtx_records_and_templates.py '{}' testp test \;
</pre>

**Comment by williballenthin** [comment]
Are you using Python 2.6 by any chance?

That statement is a dict comprehension, which I believe were added in 2.7. Either way, this warrants a fix.

**Comment by gleeda** [comment]
oh nm, i figured it out :-) sorry

**Comment by williballenthin** [comment]
I don't think we'll support py2.6 for EVTXtract. Just py27 onwards (py3 works, now!).
