### ISSUE TITLE
datetime "is not JSON serializable" errors

### ISSUE THREAD

**Issue by hiddenillusion** [williballenthin/EVTXtract#6]
```
_Traceback_
datetime.datetime(2015, 1, 22, 20, 39, 18, 79180) is not JSON serializable
Traceback (most recent call last):
  File "EVTXtract\extract_lost_evtx_records.py", line 361, in extract_lost_evtx_records
    json.dumps(record["substitutions"])
 ...
  File "c:\python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2015, 1, 22, 20, 39, 18, 969793) is not JSON serializable
```

_Workaround_
Somewhat of a quick work around was to make the datetime objects strings in `extract_lost_evtx_records.py`'s extract_root_substitutions() & extract_lost_record() . Note - this raises other errors in some debug logging in `extract_lost_evtx_records.py` & `State.py` when '.isoformat("T") + "Z"' is used.

**Comment by williballenthin** [comment]
I've recently rewritten much of EVTXtract to avoid bugs like these. Please retry on the latest version. This bug should be fixed.
